- name: Copy the {{ COMPONENT }} repo 
  ansible.builtin.copy:
    src: "{{ COMPONENT }}.repo"
    dest: /etc/yum.repos.d/{{ COMPONENT }}.repo

- name: Installing {{ COMPONENT }} 
  ansible.builtin.package:
    - name: redis-6.2.11
      state: present

- name: Replace {{ COMPONENT }}  component public ip
  ansible.builtin.replace:
    path: /etc/{{ COMPONENT }}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start {{ COMPONENT }} 
  ansible.builtin.systemd:
    - name: mongod
      state: started
      enable: true

- name: Confirgure hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: hostname
