- name: Installing Ingnix
  ansible.builtin.package:
    name: nginx
    state: present

- name: Download {{ COMPONENT }} component
  ansible.builtin.include_role:
    name: common 

- name: Clean-up nginx old content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Copy the {{ COMPONENT }} component which is downloaded on the remote machines nginx path 
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy {{ COMPONENT }} component config to nginx
  ansible.builtin.templates:
    src: "{{ APPUSER }}.conf"
    dest: /etc/nginx/default.d/{{ APPUSER }}.conf

- name: Starting Ingnix
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enable: true